### PR TITLE
Allow video only mode in RtspCamera2

### PR DESCRIPTION
**Pull request by linean**
Hi Pedro, at first I would like to thank you for the great library! It makes our lives easier ❤️ 

The current `RtspCamera2` version does not allow to enable video only mode and the only way to achieve it is to implement your own `Camera2Base`. I don't see any reason why this couldn't be added so hence my PR.

Tell me what do you think.

### CODE REVIEW

**Comment by pedroSG94** [comment]
Hello,

Camera1 and Camera2 already support stream only video if you skip call prepareAudio that disable audio in encoder module.
With your line you disable audio in rtsp module level but microphone is still in use.
I think that the best way is add this PR and document it in the wiki to avoid confusions (ideally you should disable audio in both).
Also, one thing before merge. Please, add this method to RtmpCamera1, RtspCamera1 and RtmpCamera2 to keep all consistent.

After that, I will create an entry in wiki and merge this PR

**Comment by linean** [comment]
I added setOnlyVideo to all cameras. 

> already support stream only video if you skip call prepareAudio

Even if I skip `prepareAudio` and call `disableAudio`, `RtspClient` still configures audio track.

**Comment by pedroSG94** [comment]
> I added setOnlyVideo to all cameras.
> 
> > already support stream only video if you skip call prepareAudio
> 
> Even if I skip `prepareAudio` and call `disableAudio`, `RtspClient` still configures audio track.

Yes, because it is disabled only in encoder module so rtsp or rtmp module still send audio track using default audio config. For this reason I told you this:


> With your line you disable audio in rtsp module level but microphone is still in use.
> I think that the best way is add this PR and document it in the wiki to avoid confusions (ideally you should disable audio in both).


So this is the proper way to do it:
```java
//disable audio in rtmp module to avoid send/configure audio track
rtmpCamera2.setOnlyVideo(true); 
//skip prepareAudio to disable audio in encoder module (avoid create/use AudioRecord and AudioEncoder)
if (rtmpCamera2.prepareVideo()) { 
  rtmpCamera2.startStream(endpoint);
}
```
In the future I will implement other way to do it easier to understand

**Comment by pedroSG94** [comment]
Maybe this is a better solution (it is a git .patch):
[onlyVideoPatch.zip](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/files/8543761/onlyVideoPatch.zip)
What do you think about it? With this if you skip prepareAudio the effect is the same that the code above.

**Comment by linean** [comment]
> Maybe this is a better solution (it is a git .patch):

I think it's much better, end user doesn't need to care about RTSP client configuration details 💪

**Comment by pedroSG94** [comment]
I added this change in this commit:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/0b14cad9e4ee5eb3743550060fb8b47c6aaf29a0

Closing PR because this commit solve the problem. Thank you for your time

**Comment by linean** [comment]
Great, thanks!

**Pull request closed without merging**
