### PR TITLE
Pausing audio and video decoder

### PR DESCRIPTION
**Pull request by Fruchtzwerg94**
Occuring stream TCP timeout not handled yet

### CODE REVIEW

**Comment by pedroSG94** [comment]
If you pause decoder, the stream will stop in some servers because you are not sending packets. So this isn't a general solution and I need check it.
About "stream TCP timeout", what do you mean?

**Comment by Fruchtzwerg94** [comment]
Yes you are right, it is no TCP-timeout. Like you already said:

> stream will stop in some servers because

The timeout occurs due to no packages received. Do you have an idea if it is possible to send some empty packages in this case? This could allow to keep the stream alive.

**Comment by pedroSG94** [comment]
> Do you have an idea if it is possible to send some empty packages in this case?

With audio this is easy. You can do something like this (send an empty buffer with same size of normal buffer):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/audio/MicrophoneManager.java#L177

But with video this is not easy because you need render a surface. I'm not sure if you can do it with video.

**Comment by pedroSG94** [comment]
Mute in Audio decoder is already developed but in this case you need stop extract frames from MediaExtractor.

**Pull request closed without merging**
