### PR TITLE
Stream flipping

### PR DESCRIPTION
**Pull request by marcin-adamczewski**
Hi @pedroSG94 ,
We need to add flipping only for a stream. The uses case is that the stream should be flipped for the front camera in order for branding, texts to display correctly for the watchers. On the other hand, the preview shouldn't be flipped so user can see how he/she is dancing.

I've also added a callback to notify when camera has been changed so it is easier to react on that.
I've added sample code to OpenGLRtmpActivity to visualize that, but it can be removed.
Let me know what you think.

### CODE REVIEW

**Comment by AlexUrrutia** [comment]
We definitely need this ASAP! Thanks!

**Comment by marcin-adamczewski** [comment]
FYI, I've found one issue with it. Fixing it now.

**Comment by pedroSG94** [comment]
Hello,
This change is good but camera callback is unnecessary because you have this method to know if you are using front camera:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/base/Camera2Base.java#L146
You can replace with this:
```java
rtmpCamera.switchCamera();
rtmpCamera.getGlInterface().setIsStreamHorizontalFlip(rtmpCamera.isFrontCamera());
```
I will adapt commit and merge it soon

**Comment by marcin-adamczewski** [comment]
@pedroSG94  I've the callback for two reasons:
1. camera switch can fail, so you can't be sure if it has changed
2. you can also get initial camera facing using this callback

**Comment by marcin-adamczewski** [comment]
@pedroSG94 No hurry. I'm using it on my fork so far. 
I'll try to implement it for Camera1 as well

**Comment by marcin-adamczewski** [comment]
Done, I've also reverted back the OpenGLRTMP sample to use Camera1.

**Pull request merged**
