### PR TITLE
Option disable logs

### PR DESCRIPTION
**Pull request by svprdga**
Right now the library is outputting an enormous amount of logs, I added an option to disable them.

### CODE REVIEW

**Comment by AlexUrrutia** [comment]
Thanks a lot, that was really needed

**Comment by pedroSG94** [comment]
Hello,

I prefer create a method to set value instead of set it in all constructors. This feels more cleaner for me, it avoid change code after update library version and you can do it on fly. Also I want add this to RTSP.
I will let you few days if you want update PR or discuss about it in this post to find a better solution. After that, I will merge the final solution.

If you want do it in old version you can do it using proguard.

**Comment by AlexUrrutia** [comment]
Hi Pedro, I think there must be a flag somewhere to enable/disable logs and then from there anyone can choose

**Comment by pedroSG94** [comment]
What do you means with "flag"?
I means something similar to a method in RtmpCamera1 like this:
```java
public void setLogs(boolean enabled) {
  srsFlvMuxer.setLogs(enabled);
}
```

**Comment by AlexUrrutia** [comment]
Yeah just that a Boolean, 🙂

**Comment by svprdga** [comment]
Sure, I'll change the implementation for  a cleaner solution that won't affect existing clients.

**Comment by svprdga** [comment]
I removed the option from the constructors and added a setter method instead as you suggested. I have never seen before the depths of the library so I don't know if I missed something, if anything should be done differently please tell me and I will change it.

**Comment by pedroSG94** [comment]
I fixed a bug in RTSP and merged it. Thank for your PR!

**Pull request merged**
