### PR TITLE
BaseRecordController

### PR DESCRIPTION
**Pull request by FunnyDevs**
Created the BaseRecordController component to allow setting up a custom RecordController to record video in other formats that accept h264 and aac or in mp4 using something different from AndroidMuxer (Xuggler or JCodec for example)
By default the AndroidMuxerRecordController class is used.

### CODE REVIEW

**Comment by pedroSG94** [comment]
I like it.
I will modify it a bit to fix a bug found and merge.

**Comment by pedroSG94** [comment]
I fixed all and refactored the code.
Thank you for sharing :)

**Comment by FunnyDevs** [comment]
Thank you pedro for your library :)!
As soon as possibile i create a repo with 2-3 recordcontroller i wrote (i must refactor some code) so then you'll decide if create a new repo as [RTSP-Server](https://github.com/pedroSG94/RTSP-Server)

**Comment by pedroSG94** [comment]
I will add it to README for sure but I'm not sure if create my own repo or only fork it.
I think the fork is the best solution because the code is yours.

**Comment by FunnyDevs** [comment]
Hello pedro! 
I have created a repo with two recordcontrollers ;).

https://github.com/FunnyDevs/rtmp-rtsp-stream-client-java-recordcontrollers

**Comment by pedroSG94** [comment]
> Hello pedro! I have created a repo with two recordcontrollers ;).
> 
> https://github.com/FunnyDevs/rtmp-rtsp-stream-client-java-recordcontrollers


I like it but only one hint.
Instead of set video configuration in constructor you can get it from MediaFormat like this:
```java
    @Override
    public void setVideoFormat(MediaFormat videoFormat, boolean isOnlyVideo) {
        int width = videoFormat.getInteger(MediaFormat.KEY_WIDTH);
        int height = videoFormat.getInteger(MediaFormat.KEY_HEIGHT);
        int fps = videoFormat.getInteger(MediaFormat.KEY_FRAME_RATE);
        int videoBitrate = videoFormat.getInteger(MediaFormat.KEY_BIT_RATE);
    }

    @Override
    public void setAudioFormat(MediaFormat audioFormat, boolean isOnlyVideo) {
        int sampleRate = audioFormat.getInteger(MediaFormat.KEY_SAMPLE_RATE);
        int channels = audioFormat.getInteger(MediaFormat.KEY_CHANNEL_COUNT);
        int audioBitrate = audioFormat.getInteger(MediaFormat.KEY_BIT_RATE);
        //I should get a way to notify you this if necessary. It isn't a proper way to do it.
        int sampleSize = new MicrophoneManager(null).getMaxInputSize();
    }
```

This is the real usage of this methods and by this way you can make it really easy to use because you don't need know anything about your configuration. It is configured with stream object parameters.

**Comment by pedroSG94** [comment]
I don't recommend it. 

Stream without audio or without video are supported so I recommend you change record status when the last of both is called.
One way is use 2 bolleans to know if that method was called and start record when both boolean are true 
Also, If you can support record only video or only audio it is better to fully support all record modes.
You can know it using "boolean isOnlyVideo" (in setAudioFormat it should be named isOnlyAudio, it is a typo)

**Comment by FunnyDevs** [comment]
Ok, i should have modified the files but, before pushing them, i would like to finish testing onlyVideo and onlyAudio conditions. 
To test onlyVideo i have called only `prepareVideo()`, but how could i test onlyAudio? If I call `prepareAudio()` without `prepareVideo()` i obtain a crash 

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaCodec.setCallback(android.media.MediaCodec$Callback, android.os.Handler)' on a null object reference
        at com.pedro.encoder.BaseEncoder.initCodec(BaseEncoder.java:70)
        at com.pedro.encoder.BaseEncoder.start(BaseEncoder.java:61)
```

**Comment by pedroSG94** [comment]
You can use RtmpOnlyAudio class

**Pull request merged**
