### PR TITLE
Tap to focus functionality to Camera1

### PR DESCRIPTION
**Pull request by mustafaboleken**
Not very sensitive and need to little long press but we can tweak it later.

### CODE REVIEW

**Comment by pedroSG94** [comment]
Hello,

This a good funcionality and is working for camera1. 
Also, this value, I'm not sure if this should be constant (I wrote it only for testing purposes):
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L485 
After that, the only problem is camera2.

**Comment by mustafaboleken** [comment]
I am currently working on camera2, then we will discuss about the correct weight of Camera.area

**Comment by iqiluwxy** [comment]
Why do I run demo tips Disconnect

**Comment by iqiluwxy** [comment]
Do I have to write my user name and password

**Comment by pedroSG94** [comment]
I merged this because it is 20 days without update. Please, open other MR if you finally update it for camera2

**Pull request merged**
