### PR TITLE
Display base: do not require audio permission if the streaming doesn't contain audio

### PR DESCRIPTION
**Pull request by svprdga**
I changed the DisplayBase in order to not require the audio permission if the audio is not enable.

Permissions should only be requested when is absolutely necessary, and in case of doing an only-video streaming the audio permission is not necessary at all.

### CODE REVIEW

**Comment by sergeych** [comment]
Please merge it! Its hard to explain to users why our camera-only application requires sound recording. I've tried with master, it does not work without RECORD_AUDIO...

**Comment by svprdga** [comment]
@sergeych I have forked this project with this fix done because I needed it same as you, you can use my version if you want: 

com.github.svprdga.rtmp-rtsp-stream-client-java:rtplibrary:c445e09ce496c4af1c6bff5508867b48f29ca793

**Comment by sergeych** [comment]
> @sergeych I have forked this project with this fix done because I needed it same as you, you can use my version if you want:
> 
> com.github.svprdga.rtmp-rtsp-stream-client-java:rtplibrary:c445e09ce496c4af1c6bff5508867b48f29ca793

Thanks! looks like I'll have to.

**Comment by sergeych** [comment]
> @sergeych I have forked this project with this fix done because I needed it same as you, you can use my version if you want:
> 
> com.github.svprdga.rtmp-rtsp-stream-client-java:rtplibrary:c445e09ce496c4af1c6bff5508867b48f29ca793

Can you rebase your changes on top of the current state? several updates that are not included in your branch seems to be important

**Comment by svprdga** [comment]
> > @sergeych I have forked this project with this fix done because I needed it same as you, you can use my version if you want:
> > com.github.svprdga.rtmp-rtsp-stream-client-java:rtplibrary:c445e09ce496c4af1c6bff5508867b48f29ca793
> 
> Can you rebase your changes on top of the current state? several updates that are not included in your branch seems to be important

Done: com.github.svprdga.rtmp-rtsp-stream-client-java:rtplibrary:7c20707caa6f8631edc4045caca5f32696ed861d

**Comment by sergeych** [comment]
> > > @sergeych I have forked this project with this fix done because I needed it same as you, you can use my version if you want:
> > > com.github.svprdga.rtmp-rtsp-stream-client-java:rtplibrary:c445e09ce496c4af1c6bff5508867b48f29ca793
> > 
> > 
> > Can you rebase your changes on top of the current state? several updates that are not included in your branch seems to be important
> 
> Done: com.github.svprdga.rtmp-rtsp-stream-client-java:rtplibrary:7c20707caa6f8631edc4045caca5f32696ed861d

Thanks :) hope the author will merge it so we can use it as the dependency too.

**Comment by pedroSG94** [comment]
I was not a fan of this change because don't implement anything (stream without audio is already possible doing a mute microphone). 
I will rectify my decision.
Merged, sorry for take that time.

**Pull request merged**
