### PR TITLE
Adding Preview & setting texture aspect ratio

### PR DESCRIPTION
**Pull request by MikeMannox**

### CODE REVIEW

**Comment by pedroSG94** [comment]
startPreview and stopPreview are not tested on multiple devices so I can't add this for now. I will let it open for now and test more this week.

**Comment by MikeMannox** [comment]
That is fine, I presumed it was a WIP, however, it seems that the `AutoFitTextureView` does need its aspect ratio set for preview to render correctly (it seems that this issue is present across all the sample Activities)

**Comment by pedroSG94** [comment]
If the preview problem is with front camera with a mirrored preview. That is normal, open your camera app and see this. If you take a object with letters and put in the camera you can see that is mirror preview, now take a photo and you will see all ok same with a video.

If you say other problem then specify me because I don't see other thing.

**Comment by MikeMannox** [comment]
@pedroSG94 is this example OK to be merged, or do you envisage `preview` being activated in another manner?

**Comment by MikeMannox** [comment]
@pedroSG94 
I have also spotted an issue.
I can start a preview, then start a stream, then stop a stream, expected behaviour is for preview to continue, and _only_ stop when `stopPreview()` is called

**Comment by pedroSG94** [comment]
Ah no that was intentional. Do you think that is better continue preview?
Add start preview to rtsp activity too and I merge the pull request, only on rtmp look so rare

**Comment by MikeMannox** [comment]
@pedroSG94 
Yes, I do - look at other apps for example, lets look at a normal camera app:
  * open app
    * shows preview
  * press record video
  * press stop record
  * preview continues

The app idea I am working on would have similar functionality. With the current configuration the _user_ would need to restart the app each time

**Comment by MikeMannox** [comment]
I have added the `TextureModeRtspActivity` example

By the way, I was trying to figure out how to maintain _preview_ with a colleague but could not see a solution. I'll be interested in seeing your solution :)

**Comment by pedroSG94** [comment]
Merge pull. I will update no stop preview when press stopStream today if I can

**Comment by pedroSG94** [comment]
no stop preview feature added

**Comment by MikeMannox** [comment]
👍  great

**Pull request merged**
